- name: 'Wordpress user enumeration'
  pattern: '/wp-json/wp/v2/users/'
  matcher: 'author'

- name: 'PHP info File disclosure'
  pattern: '/phpinfo.php'
  matcher: 'license@php.net'

- name: 'Dotenv file disclosure'
  pattern: '/.env'
  matcher: 'APP_URL'

- name: 'Wordpress directory Listing'
  pattern: '/wp-includes/'
  matcher: 'Index of'

- name: 'npm log file'
  pattern: '/npm-debug.log'
  matcher: 'verbose cli'

- name: 'Bitbucket pipelines'
  pattern: '/bitbucket-pipelines.yml'
  matcher: 'pipelines:'

- name: '.git folder'
  pattern: '/.git/'
  matcher: 'Index of /.git'